#!/usr/bin/env bash
# displays [To infinity and beyond] indefinitely
# with [sleep 2] in between each iteration
trap interrup SIGTERM

interrup()
{
	echo "I am invincible"
}

while true
do
	echo "To infinity and beyond"
	sleep 2
done
