#!/usr/bin/env bash
# displays Best School 10X, 9th iteration displays Best School + Hi on newline
# must: use while & if loops

i=1

while [ $i -le 10 ]
do
	echo "Best School"
	if [[ $i -eq 9 ]]
	then
		echo "Hi"
	fi
	((i++))
done
	
