#!/usr/bin/env bash
# 4th itr: bad luck, 8th itr: good luck
# must use: while, if, elif, else

i=1
a="Best School"
b="bad luck"
c="good luck"

while [ $i -le 10 ]
do
	echo "$a"
	if [[ $i -eq 4 ]]
	then
		echo "$b"
	elif [[ $i -eq 8 ]]
	then
		echo "$c"
	fi
	((i++))
done
