#!/usr/bin/env bash
# displays the time for 12h and 59m
# must use: while loop (for and until forbidden)

a=0
b=1
while [ "$a" -le 59 ]
do
	echo "Hour:$a"
	b=1
	while [ "$b" -le 59 ]
	do
		echo "$b"
		((b++))
	done
	((a++))
done
